# SQL in Python

In [8]:
import sqlite3
import pandas as pd

In [4]:
# Create database in sql 

conn = sqlite3.connect('test_database.sqlite')

#table details
conn.execute("CREATE TABLE users (first_name TEXT, country TEXT, budget INTEGER)")

# commit and save
conn.commit()

In [6]:
# insert data 

cursor = conn.cursor()

# write sql query to insert data in sql table
cursor.execute(
    """
        INSERT INTO users VALUES 
        ('Abhishek', 'India', 1000000),
        ('Madhav', 'India', 5000000),
        ('Manish', 'US', 10000),
        ('Rohit', 'Russia', 900000)
    """
)

# commit and save
conn.commit()

print("Data Inserted Succesfully")

Data Inserted Succesfully

# check inserted data into table

In [12]:
conn = sqlite3.connect('test_database.sqlite')

# query 
query = """ SELECT * FROM users"""

df_result = pd.read_sql(query ,conn)

df_result

In [13]:
df_result

  first_name country   budget
0   Abhishek   India  1000000
1     Madhav   India  5000000
2     Manish      US    10000
3      Rohit  Russia   900000
4   Abhishek   India  1000000
5     Madhav   India  5000000
6     Manish      US    10000
7      Rohit  Russia   900000

In [11]:
# aggregation 
query = """
        SELECT country, sum(budget) as Total_budget
        FROM users
        GROUP BY country;
"""
df_agg = pd.read_sql(query ,conn)

df_agg

  country  Total_budget
0   India      12000000
1  Russia       1800000
2      US         20000

In [14]:
query = "SELECT * FROM users"
df_result = pd.read_sql(query, conn)

print(df_result.shape)
df_result

(8, 3)

  first_name country   budget
0   Abhishek   India  1000000
1     Madhav   India  5000000
2     Manish      US    10000
3      Rohit  Russia   900000
4   Abhishek   India  1000000
5     Madhav   India  5000000
6     Manish      US    10000
7      Rohit  Russia   900000

In [15]:
# always close the conn of db afer over the work
conn.close()